package com.yyt.print.product.pojo;

import java.util.Date;

public class MallProductExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_ext.id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    private int id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_ext.type
     * 0 库存位置
     * 1 运费模板
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    private int type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_ext.goods_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    private int goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_ext.product_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    private int productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_ext.thrid_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    private int thridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_ext.create_time
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_product_ext.update_time
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_ext.id
     *
     * @return the value of mall_product_ext.id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_ext.id
     *
     * @param id the value for mall_product_ext.id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_ext.type
     *
     * @return the value of mall_product_ext.type
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public int getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_ext.type
     *
     * @param type the value for mall_product_ext.type
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_ext.goods_id
     *
     * @return the value of mall_product_ext.goods_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public int getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_ext.goods_id
     *
     * @param goodsId the value for mall_product_ext.goods_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public void setGoodsId(int goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_ext.product_id
     *
     * @return the value of mall_product_ext.product_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_ext.product_id
     *
     * @param productId the value for mall_product_ext.product_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public void setProductId(int productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_ext.thrid_id
     *
     * @return the value of mall_product_ext.thrid_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public Integer getThridId() {
        return thridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_ext.thrid_id
     *
     * @param thridId the value for mall_product_ext.thrid_id
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public void setThridId(int thridId) {
        this.thridId = thridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_ext.create_time
     *
     * @return the value of mall_product_ext.create_time
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_ext.create_time
     *
     * @param createTime the value for mall_product_ext.create_time
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_product_ext.update_time
     *
     * @return the value of mall_product_ext.update_time
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_product_ext.update_time
     *
     * @param updateTime the value for mall_product_ext.update_time
     *
     * @mbg.generated Thu Feb 16 17:07:33 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}