package com.yyt.print.product.pojo;

import java.util.Date;

public class MallGoodBasePro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_good_base_pro.id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    private int id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_good_base_pro.goods_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    private int goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_good_base_pro.class_pro_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    private int classProId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_good_base_pro.class_pro_value_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    private String classProValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_good_base_pro.create_time
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_good_base_pro.update_time
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_good_base_pro.id
     *
     * @return the value of mall_good_base_pro.id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_good_base_pro.id
     *
     * @param id the value for mall_good_base_pro.id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_good_base_pro.goods_id
     *
     * @return the value of mall_good_base_pro.goods_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public int getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_good_base_pro.goods_id
     *
     * @param goodsId the value for mall_good_base_pro.goods_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public void setGoodsId(int goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_good_base_pro.class_pro_id
     *
     * @return the value of mall_good_base_pro.class_pro_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public int getClassProId() {
        return classProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_good_base_pro.class_pro_id
     *
     * @param classProId the value for mall_good_base_pro.class_pro_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public void setClassProId(int classProId) {
        this.classProId = classProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_good_base_pro.class_pro_value_id
     *
     * @return the value of mall_good_base_pro.class_pro_value_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public String getClassProValue() {
        return classProValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_good_base_pro.class_pro_value_id
     *
     * @param classProValue the value for mall_good_base_pro.class_pro_value_id
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public void setClassProValue(String classProValue) {
        this.classProValue = classProValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_good_base_pro.create_time
     *
     * @return the value of mall_good_base_pro.create_time
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_good_base_pro.create_time
     *
     * @param createTime the value for mall_good_base_pro.create_time
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_good_base_pro.update_time
     *
     * @return the value of mall_good_base_pro.update_time
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_good_base_pro.update_time
     *
     * @param updateTime the value for mall_good_base_pro.update_time
     *
     * @mbg.generated Sun Feb 26 07:52:36 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}