package com.yyt.print.product.pojo;

import java.util.Date;

public class ShopUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    private int id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.shop_id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    private int shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.user_id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    private int userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.type
     * 1 店铺创建者
     * 2 店员
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    private int type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.create_time
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.id
     *
     * @return the value of shop_user.id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.id
     *
     * @param id the value for shop_user.id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.shop_id
     *
     * @return the value of shop_user.shop_id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public int getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.shop_id
     *
     * @param shopId the value for shop_user.shop_id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.user_id
     *
     * @return the value of shop_user.user_id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public int getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.user_id
     *
     * @param userId the value for shop_user.user_id
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.type
     *
     * @return the value of shop_user.type
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public int getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.type
     *
     * @param type the value for shop_user.type
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.create_time
     *
     * @return the value of shop_user.create_time
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.create_time
     *
     * @param createTime the value for shop_user.create_time
     *
     * @mbg.generated Thu Feb 23 22:09:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "ShopUser{" +
                "id=" + id +
                ", shopId=" + shopId +
                ", userId=" + userId +
                ", type=" + type +
                ", createTime=" + createTime +
                '}';
    }
}